# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{more}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["August Lilleaas", "Logan Raarup"]
  s.date = %q{2011-01-11}
  s.description = %q{More is a plugin for Ruby on Rails applications. It automatically parses your applications .less files through LESS and outputs CSS.}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Rakefile",
    "init.rb",
    "lib/less/more.rb",
    "lib/more.rb",
    "lib/more/controller_extension.rb",
    "lib/more/railtie.rb",
    "lib/tasks/more_tasks.rake",
    "rails/init.rb",
    "test/controller_test.rb",
    "test/more_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/cloudhead/more}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{LESS on Rails}
  s.test_files = [
    "test/controller_test.rb",
    "test/more_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<less>, [">= 0"])
    else
      s.add_dependency(%q<less>, [">= 0"])
    end
  else
    s.add_dependency(%q<less>, [">= 0"])
  end
end

